//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone_T
    {
        public int Phone_IDNO { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Address_IDNO { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Address_T Address_T { get; set; }
    }
}
